{% set name = "dlt" %}
{% set version = "1.17.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 7ed958f8fdb180877393e1dfa3d208892a47cdcc917e27e5dd1dacf81d8b475a
  # for testing
  - url: https://github.com/dlt-hub/dlt/archive/refs/tags/{{ version }}.tar.gz
    sha256: 0fcb70802de7d579b74e3e786d0e5039dd0d5209cb47e6844969bc27612b1c0e
    folder: gh_src

build:
  skip: True  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - dlt = dlt.cli._dlt:_main

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - requests >=2.26.0
    - pendulum >=2.1.2
    - pendulum >=3.0.0  # [py>313]
    - dlt-pendulum >=3.0.2
    - simplejson >=3.17.5
    - pyyaml >=5.4.1
    - semver >=3.0.0
    - hexbytes >=0.2.2
    - python-tzdata >=2022.1
    - tomlkit >=0.11.3
    - pathvalidate >=2.5.2
    - typing_extensions >=4.8.0
    - click >=7.1
    - requirements-parser >=0.5.0
    - setuptools >=65.6.0
    - humanize >=4.4.0
    - gitpython >=3.1.29
    - pytz >=2022.6
    - giturlparse >=0.10.0
    - orjson >=3.6.7,<4,!=3.9.11,!=3.9.12,!=3.9.13,!=3.9.14,!=3.10.1
    - orjson >=3.11.0  # [py>313]
    - tenacity >=8.0.2
    - jsonpath-ng >=1.5.3
    - fsspec >=2022.4.0
    - packaging >=21.1
    - pluggy >=1.3.0
    - win-precise-time >=1.4.2  # [win and py<313]
    - sqlglot >=25.4.0
    - rich-argparse >=1.6.0
  run_constrained:
    # There's more, but since it's going to the snowflake channel, we only need this
    - snowflake-connector-python >=3.5.0

{% set tests_to_skip = [
  # assumes editable install
  "test_installed_requirement_string",
  "test_import_unknown_destination",
  "test_run_context",
  # assumes venv
  "test_current_base_python",
  # upstream bug in _uuid_expr_for_dialect
  "test_simple_model_normalizing",
  # assumes unprivileged runner 
  "test_hard_link_fallback",  # [linux]
] %}

{% set tests_requiring_connection = [
  # tests from snowflake subdir that require connection to real database
  # tests/load/snowflake
  "test_session_autocommit",
  "test_create_table_with_hints",
  "test_query_tag",
  "test_create_table",
  "test_alter_table",
  "test_create_table_case_sensitive",
  "test_create_table_with_partition_and_cluster",
  # tests/load/pipeline/test_snowflake_pipeline.py
  "test_snowflake_case_sensitive_identifiers",
  "test_snowflake_query_tagging",
  "test_snowflake_custom_stage",
  "test_snowflake_delete_file_after_copy",
  "test_char_replacement_cs_naming_convention",
  "test_snowflake_use_vectorized_scanner",
] %}

test:
  files:
    - test/test_basic_functionality.py
  source_files:
    - gh_src
  imports:
    - dlt
  requires:
    - pip
    - python
    - pytest-console-scripts >=1.4.1,<2
    - pytest >=7.4.4,<8
    - requests-mock >=1.10.0,<2
    - pytest-forked >=1.3.0
    - pytest-mock >=3.14.0,<4
    - pytest-asyncio >=0.23.5,<0.24
    - sqlalchemy <2
    - snowflake-connector-python
    - sentry-sdk >=2.0.0,<3
    - sqlfluff >=2.3.2           # [py<313]
    - cryptography >=41.0.7,<42  # [py<313]
    - git  # [linux]
  commands:
    - dlt --help
    - pip check
    # Basic functionality test
    - python test/test_basic_functionality.py  # [not win]
    - cd gh_src
    # Core tests
    - pytest -vv tests/common -k "not ({{ tests_to_skip|join(' or ') }})"
    - pytest -vv tests/normalize -k "not ({{ tests_to_skip|join(' or ') }})"
    # Snowflake-specific tests
    # missing sqlfluff and cryptography for py313
    - pytest -vv tests/load/snowflake -k "not ({{ tests_requiring_connection|join(' or ') }})"  # [py<313]
    - pytest -vv tests/load/pipeline/test_snowflake_pipeline.py -k "not ({{ tests_requiring_connection|join(' or ') }})"  # [py<313]

about:
  summary: dlt is an open-source python-first scalable data loading library that does not require any backend to run.
  license: Apache-2.0
  license_file: LICENSE.txt
  license_family: Apache
  home: https://dlthub.com/docs
  description: |
    data load tool (dlt) is an open source Python library that makes data loading easy.
  dev_url: https://github.com/dlt-hub/dlt
  doc_url: https://dlthub.com/docs


extra:
  recipe-maintainers:
    - rudolfix
    - rxm7706
    - sultaniman
